In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("C:\ITvedant\Data Manipulation\Retail_Dataset_Cleaned lab 7.csv")
	
 
print("Dataset Loaded Successfully")

Dataset Loaded Successfully

<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
C:\Users\snehal\AppData\Local\Temp\ipykernel_18084\2254315882.py:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
  df = pd.read_csv("C:\ITvedant\Data Manipulation\Retail_Dataset_Cleaned lab 7.csv")

In [4]:
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,Bx_Pune_034,Brandx_India Superstore Pune,Brandx_India,Flagship,Pune,Tier1,Green Tea 100G,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,Bx_Mumbai_023,Brandx_India Superstore Mumbai,Brandx_India,Street Store,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,Bx_Pune_073,Brandx_India Trends Pune,Brandx_India,Flagship,Pune,Tier1,Levi'S T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,Bx_Chennai_061,Brandx_India Trends Chennai,Brandx_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,Bx_Chennai_033,Brandx_India Connect Chennai,Brandx_India,Mall Store,Chennai,Metro,Playstation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5146 entries, 0 to 5145
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5146 non-null   str
 1   Store_Name             5146 non-null   str
 2   Brand_Name             5146 non-null   str
 3   Store_Type             5146 non-null   str
 4   City                   5146 non-null   str
 5   City_Tier              5146 non-null   str
 6   Product_Name           5146 non-null   str
 7   Category               5146 non-null   str
 8   Sub_Category           5146 non-null   str
 9   Product_Stage          5146 non-null   str
 10  Quantity_Available     5146 non-null   float64
 11  Units_Sold             5146 non-null   float64
 12  Unit_Price             5146 non-null   int64
 13  Cost_Price             5146 non-null   int64
 14  Revenue                5146 non-null   float64
 15  Profit_Margin          5146 non-null   float64
 16  Average_Order_Value    5146 non-null   int64
 17  Inventory_Turnover     5146 non-null   float64
 18  Days_of_Stock          5146 non-null   int64
 19  Customer_Segment       5146 non-null   str
 20  Sales_Channel          5146 non-null   str
 21  Payment_Method         5146 non-null   str
 22  Supplier               5146 non-null   str
 23  Supplier_Rating        5146 non-null   str
 24  Promotion_Type         5146 non-null   str
 25  Promotion_Impact       5146 non-null   float64
 26  Max_Discount_Offered   5146 non-null   int64
 27  Return_Rate            5146 non-null   float64
 28  Return_Reason          5146 non-null   str
 29  Customer_Satisfaction  5146 non-null   float64
 30  Online_Rating          5146 non-null   float64
 31  Review_Count           5146 non-null   int64
 32  Sales_Rep_Experience   5146 non-null   int64
 33  Sales_Rep_Rating       5146 non-null   float64
 34  Market_Share           5146 non-null   float64
 35  Competition_Level      5146 non-null   str
 36  Competitor_Count       5146 non-null   int64
 37  Brand_Loyalty          5146 non-null   float64
 38  Brand_Awareness        5146 non-null   float64
 39  Price_Competitiveness  5146 non-null   str
 40  Weather_Impact         5146 non-null   str
 41  Delivery_Time          5146 non-null   float64
 42  Shipping_Cost          5146 non-null   float64
 43  Month                  5146 non-null   int64
 44  Year                   5146 non-null   int64
 45  Quarter                5146 non-null   str
 46  Season                 5146 non-null   str
dtypes: float64(15), int64(10), str(22)
memory usage: 1.8 MB

In [6]:
revenue_variance = df["Revenue"].var()
print("Revenue Variance:", revenue_variance)

Revenue Variance: 5697748931696.269

In [7]:
revenue_std = df["Revenue"].std()
print("Revenue Standard Deviation:", revenue_std)

Revenue Standard Deviation: 2386995.796329828

In [8]:
comparison = pd.DataFrame({
    "Metric": ["variance", "Standard Deviation"],
    "Value" : [revenue_variance, revenue_std]
})

comparison

               Metric         Value
0            variance  5.697749e+12
1  Standard Deviation  2.386996e+06

In [11]:
units_variance = df["Units_Sold"].var()
print("Units Sold Variance:", units_variance)

Units Sold Variance: 723.5115957104068

In [14]:
units_sold = df["Units_Sold"].std()

print("Units Sold Standard Deviation:", units_std)

Units Sold Standard Deviation: 26.898170861796658

In [15]:
delivery_std = df["Delivery_Time"].std()
print("Delivery TIme Standard Deviation:, delivery_std")

Delivery TIme Standard Deviation:, delivery_std

In [18]:
df["Revenue"].mean()

np.float64(1376186.72813836)

In [19]:
df["Revenue"].median()

np.float64(350176.0)

In [20]:
df["Revenue"].mode()

0    350176.0
Name: Revenue, dtype: float64

In [21]:
df["Revenue"].value_counts()

Revenue
350176.0     80
4752.0        3
18511.0       2
5363.0        2
11025.0       2
             ..
2410485.0     1
2071622.0     1
1480392.0     1
8073.0        1
100385.0      1
Name: count, Length: 4980, dtype: int64

In [22]:
print("Revenue Variance:", revenue_variance)
print("Revenue Standard Deviation:", revenue_std)

print("Units Sold Variance:", units_variance)
print("Units Sold Standard Deviation:", units_std)

Revenue Variance: 5697748931696.269
Revenue Standard Deviation: 2386995.796329828
Units Sold Variance: 723.5115957104068
Units Sold Standard Deviation: 26.898170861796658