In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:\ITvedant\Data Manipulation\Retail_Dataset_Cleaned.csv")
print("Dataset Loaded Successfully")

Dataset Loaded Successfully

<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
C:\Users\snehal\AppData\Local\Temp\ipykernel_29616\1358963827.py:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
  df = pd.read_csv("C:\ITvedant\Data Manipulation\Retail_Dataset_Cleaned.csv")

In [3]:
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,Bx_Pune_034,Brandx_India Superstore Pune,Brandx_India,Flagship,Pune,Tier1,Green Tea 100G,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,Bx_Mumbai_023,Brandx_India Superstore Mumbai,Brandx_India,Street Store,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,Bx_Pune_073,Brandx_India Trends Pune,Brandx_India,Flagship,Pune,Tier1,Levi'S T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,Bx_Chennai_061,Brandx_India Trends Chennai,Brandx_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,Bx_Chennai_033,Brandx_India Connect Chennai,Brandx_India,Mall Store,Chennai,Metro,Playstation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring

In [4]:
df.info

<bound method DataFrame.info of             Store_ID                       Store_Name    Brand_Name  \
0        Bx_Pune_034     Brandx_India Superstore Pune  Brandx_India
1      Bx_Mumbai_023   Brandx_India Superstore Mumbai  Brandx_India
2        Bx_Pune_073         Brandx_India Trends Pune  Brandx_India
3     Bx_Chennai_061      Brandx_India Trends Chennai  Brandx_India
4     Bx_Chennai_033     Brandx_India Connect Chennai  Brandx_India
...              ...                              ...           ...
5141   Bx_Jaipur_077        Brandx_India Style Jaipur  Brandx_India
5142   Bx_Mumbai_067        Brandx_India Daily Mumbai  Brandx_India
5143   Bx_Kanpur_097  Brandx_India Gadget Zone Kanpur  Brandx_India
5144   Bx_Mumbai_031        Brandx_India Style Mumbai  Brandx_India
5145    Bx_Delhi_032   Brandx_India Electronics Delhi  Brandx_India

        Store_Type     City City_Tier     Product_Name     Category  \
0         Flagship     Pune     Tier1   Green Tea 100G    Groceries
1     Street Store   Mumbai     Metro  White Sugar 1Kg    Groceries
2         Flagship     Pune     Tier1   Levi'S T-Shirt      Clothes
3       Mall Store  Chennai     Metro    Adidas Hoodie      Clothes
4       Mall Store  Chennai     Metro    Playstation 5      Gadgets
...            ...      ...       ...              ...          ...
5141  Street Store   Jaipur     Tier2       Pepe Jeans      Clothes
5142       Express   Mumbai     Metro  White Sugar 1Kg    Groceries
5143      Flagship   Kanpur     Tier2      Dell Xps 13  Electronics
5144  Street Store   Mumbai     Metro     Nike Air Max      Clothes
5145      Flagship    Delhi     Metro   Macbook Air M2  Electronics

         Sub_Category Product_Stage  ...  Brand_Loyalty  Brand_Awareness  \
0                 Tea     Declining  ...           70.8             75.7
1               Sugar     Declining  ...           80.5             81.5
2            T-Shirts     Declining  ...           68.5             76.7
3             Jackets    New Launch  ...           92.4             88.0
4     Gaming Consoles     Declining  ...           82.9             89.5
...               ...           ...  ...            ...              ...
5141            Jeans     Declining  ...           91.3             68.7
5142            Sugar       Growing  ...           81.6             82.0
5143          Laptops  Discontinued  ...           89.9             68.1
5144            Shoes        Mature  ...           80.6             86.5
5145          Laptops     Declining  ...           91.8             85.0

      Price_Competitiveness  Weather_Impact  Delivery_Time  Shipping_Cost  \
0                  Standard             Low            6.0           57.0
1               Competitive             Low            4.0           99.0
2                  Standard          Medium            4.0          101.0
3               Competitive          Medium            5.0           79.0
4               Competitive             Low            2.0          110.0
...                     ...             ...            ...            ...
5141               Standard          Medium            3.0          150.0
5142            Competitive             Low            7.0          136.0
5143               Standard             Low            1.0          222.0
5144            Competitive          Medium            3.0          138.0
5145            Competitive             Low            3.0          210.0

      Month  Year  Quarter   Season
0         1  2022       Q1   Spring
1         1  2022       Q1   Spring
2         1  2022       Q1   Spring
3         1  2022       Q1   Spring
4         1  2022       Q1   Spring
...     ...   ...      ...      ...
5141     11  2024       Q4   Winter
5142      7  2023       Q3  Monsoon
5143      7  2023       Q3  Monsoon
5144     12  2022       Q4   Winter
5145      6  2024       Q2  Monsoon

[5146 rows x 47 columns]>

In [6]:
df["Profit_Amount"] = (
    df["Revenue"] *
    df["Profit_Margin"] / 100
)

df[["Revenue",
    "Profit_Margin",
    "Profit_Amount"]].sample(5)

        Revenue  Profit_Margin  Profit_Amount
3782    26390.0          20.74      5473.2860
2681  3984002.0          24.36    970502.8872
3254  1446510.0          19.39    280478.2890
4572   186067.0          26.19     48730.9473
3949  2699606.0          19.51    526693.1306

In [7]:
df["Stock_Difference"] = (
    df["Quantity_Available"] -
    df["Units_Sold"]
)

df[["Quantity_Available",
    "Units_Sold",
    "Stock_Difference"]].sample(5)

      Quantity_Available  Units_Sold  Stock_Difference
4545               112.0        48.0              64.0
3946               168.0        90.0              78.0
1983                97.0        22.0              75.0
2002               158.0        86.0              72.0
1241                62.0        13.0              49.0

In [8]:
df["Inventory_Status"] = np.where(
    df["Quantity_Available"] < 100,
    "Low Stock",
    np.where(
        df["Quantity_Available"] <= 200,
        "Medium Stock",
        "High Stock"
    )
)

df[["Quantity_Available",
    "Inventory_Status"]].sample(5)

      Quantity_Available Inventory_Status
4168                65.0        Low Stock
3068               217.0       High Stock
1525                96.0        Low Stock
181                126.0     Medium Stock
2560               162.0     Medium Stock

In [9]:
df["Revenue_Per_Unit"] = (
    df["Revenue"] /
    df["Units_Sold"]
)

df[["Revenue",
    "Units_Sold",
    "Revenue_Per_Unit"]].sample(5)

        Revenue  Units_Sold  Revenue_Per_Unit
4054   458225.0        25.0           18329.0
4185  1886226.0        62.0           30423.0
3140   426154.0        41.0           10394.0
3952  1350822.0        66.0           20467.0
4403  1752105.0        15.0          116807.0

In [10]:
print(df[[
    "Profit_Amount",
    "Stock_Difference",
    "Inventory_Status",
    "Revenue_Per_Unit"
]].head())

   Profit_Amount  Stock_Difference Inventory_Status  Revenue_Per_Unit
0      1584.0480             101.0     Medium Stock             305.0
1       490.0455             100.0     Medium Stock              47.0
2     13175.1240             184.0       High Stock            2140.0
3     14080.1628             141.0     Medium Stock            3534.0
4    398237.3460             128.0     Medium Stock           50676.0

In [11]:
df["Revenue_Category"] = np.where(
    df["Revenue"] < 5000,
    "Low Revenue",
    np.where(
        df["Revenue"] < 10000,
        "Medium Revenue",
        "High Revenue"
    )
)

df[["Revenue", "Revenue_Category"]].head()

     Revenue Revenue_Category
0     7320.0   Medium Revenue
1     1645.0      Low Revenue
2    66340.0     High Revenue
3    77748.0     High Revenue
4  1976364.0     High Revenue

In [12]:
df["Customer_Feedback"] = np.where(
    df["Customer_Satisfaction"] >= 4,
    "Satisfied",
    "Needs Improvement"
)

df[[
    "Customer_Satisfaction",
    "Customer_Feedback"
]].head()

   Customer_Satisfaction  Customer_Feedback
0                    4.0          Satisfied
1                    3.9  Needs Improvement
2                    4.3          Satisfied
3                    4.4          Satisfied
4                    3.9  Needs Improvement

In [13]:
df["Discount_Category"] = np.where(
    df["Max_Discount_Offered"] < 10,
    "Low Discount",
    np.where(
        df["Max_Discount_Offered"] < 20,
        "Medium Discount",
        "High Discount"
    )
)

df[["Max_Discount_Offered", "Discount_Category"]].sample(5)

      Max_Discount_Offered Discount_Category
3835                    10   Medium Discount
893                     18   Medium Discount
1555                    25     High Discount
5036                     7      Low Discount
1581                    12   Medium Discount

In [14]:
df["Delivery_Speed"] = np.where(
    df["Delivery_Time"] <= 5,
    "Fast Delivery",
    "Standard Delivery"
)

df[[
    "Delivery_Time",
    "Delivery_Speed"
]].head()

   Delivery_Time     Delivery_Speed
0            6.0  Standard Delivery
1            4.0      Fast Delivery
2            4.0      Fast Delivery
3            5.0      Fast Delivery
4            2.0      Fast Delivery

In [15]:
print(df[[
    "Revenue_Category",
    "Customer_Feedback",
    "Discount_Category",
    "Delivery_Speed"
]].head())

  Revenue_Category  Customer_Feedback Discount_Category     Delivery_Speed
0   Medium Revenue          Satisfied      Low Discount  Standard Delivery
1      Low Revenue  Needs Improvement     High Discount      Fast Delivery
2     High Revenue          Satisfied     High Discount      Fast Delivery
3     High Revenue          Satisfied     High Discount      Fast Delivery
4     High Revenue  Needs Improvement     High Discount      Fast Delivery

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5146 entries, 0 to 5145
Data columns (total 55 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5146 non-null   str
 1   Store_Name             5146 non-null   str
 2   Brand_Name             5146 non-null   str
 3   Store_Type             5146 non-null   str
 4   City                   5146 non-null   str
 5   City_Tier              5146 non-null   str
 6   Product_Name           5146 non-null   str
 7   Category               5146 non-null   str
 8   Sub_Category           5146 non-null   str
 9   Product_Stage          5146 non-null   str
 10  Quantity_Available     5146 non-null   float64
 11  Units_Sold             5146 non-null   float64
 12  Unit_Price             5146 non-null   int64
 13  Cost_Price             5146 non-null   int64
 14  Revenue                5146 non-null   float64
 15  Profit_Margin          5146 non-null   float64
 16  Average_Order_Value    5146 non-null   int64
 17  Inventory_Turnover     5146 non-null   float64
 18  Days_of_Stock          5146 non-null   int64
 19  Customer_Segment       5146 non-null   str
 20  Sales_Channel          5146 non-null   str
 21  Payment_Method         5146 non-null   str
 22  Supplier               5146 non-null   str
 23  Supplier_Rating        5146 non-null   str
 24  Promotion_Type         5146 non-null   str
 25  Promotion_Impact       5146 non-null   float64
 26  Max_Discount_Offered   5146 non-null   int64
 27  Return_Rate            5146 non-null   float64
 28  Return_Reason          5146 non-null   str
 29  Customer_Satisfaction  5146 non-null   float64
 30  Online_Rating          5146 non-null   float64
 31  Review_Count           5146 non-null   int64
 32  Sales_Rep_Experience   5146 non-null   int64
 33  Sales_Rep_Rating       5146 non-null   float64
 34  Market_Share           5146 non-null   float64
 35  Competition_Level      5146 non-null   str
 36  Competitor_Count       5146 non-null   int64
 37  Brand_Loyalty          5146 non-null   float64
 38  Brand_Awareness        5146 non-null   float64
 39  Price_Competitiveness  5146 non-null   str
 40  Weather_Impact         5146 non-null   str
 41  Delivery_Time          5146 non-null   float64
 42  Shipping_Cost          5146 non-null   float64
 43  Month                  5146 non-null   int64
 44  Year                   5146 non-null   int64
 45  Quarter                5146 non-null   str
 46  Season                 5146 non-null   str
 47  Profit_Amount          5146 non-null   float64
 48  Stock_Difference       5146 non-null   float64
 49  Inventory_Status       5146 non-null   str
 50  Revenue_Per_Unit       5146 non-null   float64
 51  Revenue_Category       5146 non-null   str
 52  Customer_Feedback      5146 non-null   str
 53  Discount_Category      5146 non-null   str
 54  Delivery_Speed         5146 non-null   str
dtypes: float64(18), int64(10), str(27)
memory usage: 2.2 MB